### ISSUE TITLE
Fixed card per row in grid

### ISSUE THREAD

**Issue by kazu93** [gjbarnard/moodle-format_grid#120]
There is no option in the grid to define a fixed amount of cards per row. This amount of cards should stay in order after page resizing or line break. Possible layout could be 2x2, 3x3 or 4x4. Or if possible, self chosen like Table sizes in Excel.

Tested on Moodle 3.7 and 3.9

**Comment by gjb2048** [comment]
@kazu93 Interesting idea!  Would you be able to fund this enhancement please?

**Comment by kazu93** [comment]
Hey, how much would that funding need be?

**Comment by gjb2048** [comment]
@kazu93 Probably 2-3 hours+ work.  I can quote to a budget holder.

**Comment by kazu93** [comment]
I would need a specific amount. I'm not asking as a private person, but for a public institution. We need to declare the specific amount and try to get it for our moodle budget.

**Comment by gjb2048** [comment]
In that case, please can I have the contact details of the budget holder and can take things from there and not conduct specific business in public.

**Comment by gjb2048** [comment]
No response, closing.
