### ISSUE TITLE
Moodle running on an ipaddress rather than a domain

### ISSUE THREAD

**Issue by sharpchi** [gjbarnard/moodle-format_grid#128]
This is something that has cropped up in testing where we're testing a Moodle (3.9.4+) Boost theme, and Grid (3.9.1.0 - 2020070701) running on an ip address rather than a domain name.
We found that when you click on "Participants" in the NavDrawer that a section opened rather than going to the users/index.php page.
![Participants Click](https://user-images.githubusercontent.com/3774280/101654085-01efbb80-3a38-11eb-81d0-3f8b3c069370.png)

Following the code in module.js, the navdrawerclick function doesn't handle href.indexOf correctly. https://github.com/gjb2048/moodle-format_grid/blob/06e0e02b458ad1ade3064defc9745983bdee1f5b/module.js#L170

When indexOf can't find the string it returns -1, but this isn't checked for, so it continues on to try to parseInt. When the href is a domain name, this just fails with NaN, but if it's an ipaddress the first numbers are returned. Our ip address started with a 10 and we found that grid was making section-10 appear when clicking on Participants.

Here are a couple of examples from the console log in Firefox mimicing what the function is doing, hopefully you can reproduce these:
Normal domain name example
![Normal domain name example](https://user-images.githubusercontent.com/3774280/101655179-36b04280-3a39-11eb-96dc-f326752cc68c.png)

Ip address example:
![IP address example](https://user-images.githubusercontent.com/3774280/101655265-50ea2080-3a39-11eb-8d4f-5f532242f589.png)

I think line 171 should read:
`if (sectionref <= 0) {`
https://github.com/gjb2048/moodle-format_grid/blob/06e0e02b458ad1ade3064defc9745983bdee1f5b/module.js#L171

Happy to do a pull request, if you think that's the fix.
thanks
Mark

**Comment by gjb2048** [comment]
@sharpchi Thanks, will look when I get time.

**Comment by gjb2048** [comment]
M4.0- versions no longer supported and this code does not exist in M4.0+ versions.
