### ISSUE TITLE
add an option to hide sections without images

### ISSUE THREAD

**Issue by jboulen** [gjbarnard/moodle-format_grid#137]
Hello,
In our institution, some teachers are looking for a solution to reduce the number of sections in their courses and to improve UX.
We found [this topic on Moodle.org](https://moodle.org/mod/forum/discuss.php?d=353131#p1513696), which shows how to use stealth activities/resources in hidden sections. That's great, however a downside to this solution is that [navigation links disappear](https://github.com/moodle/moodle/blob/511a87f5fc357f18a4c53911f6e6c7f7b526246e/lib/outputrenderers.php#L933) between activities/resources.
Would you accept a PR that implements an option to allow teachers to hide sections without images (only when editing mode is off) ?
Regards,

**Comment by gjb2048** [comment]
I'm confused as your suggested PR does not make sense as it does not relate
directly to the problem that you're describing.  In any event, I've tested
both the Grid and Topics format and activity navigation (not section) does
not operate between stealth activities - and 'activity' navigation is
outside of the control of a course format.  Course formats can only control
section navigation.

**Comment by jboulen** [comment]
I agree that course formats can't control the navigation links on the main activity pages.

Our problem is to keep navigation links on the main activity pages **and** to reduce the number of sections displayed to students.

Unless I'm wrong, it's not possible to keep navigation links on the main activity pages by hiding sections and using stealth activities.

So, we propose to add an option in grid course format settings to hide the sections that would not have a background image.

For example, on [this screenshot](https://moodle.org/pluginfile.php/155/mod_forum/post/1513696/3.JPG), this option would display to students only the first 6 sections. So, the main course page will be lighter and more readable.

**Comment by gjb2048** [comment]
Won't that be confusing when students can't access an activity from the main page, only the activity navigation or a purpose placed link?

**Comment by jboulen** [comment]
I don't think that it will be more confusing than stealth activities.

I'm not a course creator, but this seems to be a common trick used by course designers to avoid long lists of sections and activities. They seem to appreciate the ability of the grid format to reduce the list of sections. All that's missing is a way to reduce the long lists of activities.

Actually, the suggested option will introduce a kind of stealth section. But maybe you prefer that this feature comes directly from Moodle core ? There is an opened issue about this ([MDL-59481](https://tracker.moodle.org/browse/MDL-59481)).

**Comment by gjb2048** [comment]
@jboulen Ok, I see, so are you willing and able to fund my time on this please?  As even you're providing the code, then it will still take a reasonable amount on my part to review, improve, explain and maintain the additional functionality.  I have very high standards for the code.

**Comment by jboulen** [comment]
I'm going to ask the question to my institution...

**Comment by gjb2048** [comment]
@jboulen Any news on this please?

**Comment by jboulen** [comment]
No news on this. I think you can consider that my institution will not be able to fund your time on this issue.

**Comment by gjb2048** [comment]
@jboulen Thank you for letting me know.  If they change their mind and are willing to pay for a solution they want, then do please contact me again.

**Comment by gjb2048** [comment]
Funding not forthcoming, closing.
