### ISSUE TITLE
Sections revert to 10 when performing a bulk course upload

### ISSUE THREAD

**Issue by 55133829** [gjbarnard/moodle-format_grid#155]
**Plugin:** Grid
**Version:** 3.10.1.4
**Build:** 2020111405

**Moodle Version:** 3.10.8 (Build: 20211108)

We are running an up to date version of Moodle at our Organisation. At certain points in the academic year, we make bulk changes to courses, primarily to the visible field. The CSV file includes the two fields,shortname and visible.

Whichever value ( 1 or 0 ) we place in the visible column, a Gridformat course will revert to 10 sections.

**Scenario 1**
Course A is a Grid format course
Has x3 Section ( Week 1, Week 2, Week 3 )

CSV file is uploaded via the course upload function in Moodle, then x7 empty sections appear (Section-4. . .Section-10)

As a workaround, we change the sections back to 3 in the cource setting. 

**Scenario 2**
Course B is a Grid format course
Has x15 Sections ( Week 1. . .Week 15 )

CSV file is uploaded via the course upload function in Moodle, after performing the bulk upload,  x10 sections appear as though x5 sections have been removed

As a workaround, we change the sections back to 15 in the course settings and the sections appear, as though they had been hidden.

When uploading the CSV file using the Course upload function. the following options are selected:-
**Import Options Settings
Upload mode:** Only update existing courses
**Update mode:** Update with CSV data only
_**No other setting option are applied_

Could some guidance be provided because we are heavily reliant on Grid Format courses?

**Comment by gjb2048** [comment]
@55133829 I will investigate at some point.  If you require a faster response, then please consider funding my time.

**Comment by gjb2048** [comment]
@55133829 

I'm no longer supporting the M3.10 version unpaid.

G

**Comment by gjb2048** [comment]
Funding not forthcoming, closing.
