### ISSUE TITLE
PHP8.0 Compatibility issue when switching to Grid format

### ISSUE THREAD

**Issue by ClaytonDarl** [gjbarnard/moodle-format_grid#157]
Doing some testing with PHP8 for when Moodle officially supports it and came across an issue when switching over a course to the grid format.

Moodle will throw:
Exception - Unknown named parameter $size
- Stack trace: Line 704 of course/format/lib.php: Error thrown. 

I looked further into the issue and found an exact copy from another course format on the Moodle Forums [here](https://moodle.org/mod/forum/discuss.php?d=426420)

I tested out the fix for it in the forum post, and that will solve the issue. Changing lines 658, 699, 805 in course/format/grid/lib.php from:
'element_attributes' => array('size' => 3) to 'element_attributes' => array(array('size' => 3))

Happy to help fix if you would like!

**Comment by gjb2048** [comment]
Interesting, thank you @ClaytonDarl - it looks like the 'size' attribute is not being passed to the form input markup anyway, so therefore this is a bug and applying the array in array fix, solves it.

There won't be a version for M4.0+ of the format unless funded.  But this fix makes sense at the moment.

**Comment by gjb2048** [comment]
Note to self:  Leave open for a while longer in case needs backporting to M3.10- (funded)

**Comment by gjb2048** [comment]
Funding not forthcoming, closing.
