### ISSUE TITLE
When not editing #gridmiddle-column line height is set to 1.

### ISSUE THREAD

**Issue by stuartlamour** [gjbarnard/moodle-format_grid#161]
This makes text on the page, especially in paragraphs, inconsistent from other areas, squashed and difficult to read.

This is caused by the following css:

body:not(.editing) #gridmiddle-column {
    line-height: 1;
}

Removing it seems to have no impact other than to fix the issue.

**Comment by gjb2048** [comment]
@stuartlamour As the M4.0 is now a 're-write', this should not be an issue going forward.

**Comment by gjb2048** [comment]
@stuartlamour Current economics is now driving me to less free, sorry.

**Comment by gjb2048** [comment]
Funding not forthcoming, closing.
