### ISSUE TITLE
Set the image container alignment - left, middle, centre not available anymore   

### ISSUE THREAD

**Issue by nenorojas** [gjbarnard/moodle-format_grid#175]
Just checking if this option was deprecated for 4.0/4.1 version of the plugin or if it's missing due to a bug. The only way to show the icons is justified. 

**Versions (please complete the following information):**
 - Moodle: 4.1.1
 - Format: 401.0.3
 - Browser and version: Edge Windows 10

![image](https://user-images.githubusercontent.com/3680797/220596896-f3b30865-75be-4ab1-a359-ff6e30772338.png)

**Comment by gjb2048** [comment]
Implemented in #191.
