### ISSUE TITLE
format_grid upgrade locks prevents upgrade from completing

### ISSUE THREAD

**Issue by aspark21** [gjbarnard/moodle-format_grid#181]
**Describe the bug**

We've done a few upgrades from 3.11 to 4.2 and this is the first time this occurred. Had to clear out the locks folder in moodledata to resume the upgrade process

Moodle has a built-in mechanism to prevent upgrades from being run more than once at the same time so I'm very unclear on the purpose of this specific locking mechanism during the upgrade of grid 

apart from making recovery from an interrupted upgrade harder

https://github.com/gjb2048/moodle-format_grid/blob/master/db/upgrade.php#L66

```
-->format_grid
Default exception handler: Coding error detected, it must be fixed by a programmer: A lock was created but not released at:
[dirroot]/course/format/grid/db/upgrade.php on line 66

!!! Coding error detected, it must be fixed by a programmer: A lock was created but not released at:
 Code should look like:

 $factory = \core\lock\lock_config::get_lock_factory('type');
 $lock = $factory-&gt;get_lock(efc7b26255bd9190d1bb309dda1d057609d6bae5);
 $lock-&gt;release();  // Locks must ALWAYS be released like this.

 Debug: 
Error code: codingerror
* line 135 of /lib/classes/lock/lock.php: coding_exception thrown
* line 794 of /lib/upgradelib.php: call to core\lock\lock->__destruct()
* line 1974 of /lib/upgradelib.php: call to upgrade_plugins()
* line 274 of /admin/cli/upgrade.php: call to upgrade_noncore()

[dirroot]/course/format/grid/db/upgrade.php on line 66

 Code should look like:

 $factory = \core\lock\lock_config::get_lock_factory('type');
 $lock = $factory-&gt;get_lock(efc7b26255bd9190d1bb309dda1d057609d6bae5);
 $lock-&gt;release();  // Locks must ALWAYS be released like this.

 !!!
!! 
Error code: codingerror !!
!! Stack trace: * line 135 of /lib/classes/lock/lock.php: coding_exception thrown
* line 794 of /lib/upgradelib.php: call to core\lock\lock-&gt;__destruct()
* line 1974 of /lib/upgradelib.php: call to upgrade_plugins()
* line 274 of /admin/cli/upgrade.php: call to upgrade_noncore()
 !!
Error: Process completed with exit code 1.

```

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Versions (please complete the following information):**
 - Moodle: 4.2
 - Format: V402.1.0
 - CLI and browser upgrade

**Additional context**

**Comment by aspark21** [comment]
if anything this step should really be split off into an ad-hoc task that is executed after the upgrade rather than holding things up unnecessarily during the upgrade

**Comment by gjb2048** [comment]
1. The lock was added for a reason, I believe to prevent the code being executed more than once in a multi-threaded environment.
2. I cannot see how the code is wrong as the lock is released even if there is an exception.
3. The code cannot be put in an ad-hoc task as its actions need to be completed before a user accesses a Grid course.

**Comment by aspark21** [comment]
not sure if & how this was fixed but we've upgraded prod without issue so going to close this
