### ISSUE TITLE
Last topic image is missing in edit mode

### ISSUE THREAD

**Issue by babicht** [gjbarnard/moodle-format_grid#184]
Hi,
while testing some plugins before updating moodle, we encountered a problem with the grid format. When in edit mode, the image of the last topic/grid element is not displayed. Other images/topics work fine but the last one is always missing across multiple test courses.
![grafik](https://github.com/gjb2048/moodle-format_grid/assets/136691601/42910963-c682-47a0-8e3e-d76afe957a10)

I tried to look into the code and discovered that the image is not present in the DOM so I guess it's maybe not being generated by the plugin/format:
![grafik](https://github.com/gjb2048/moodle-format_grid/assets/136691601/070967d9-e187-4ab2-8c97-939000703604)

**Versions**
- Moodle: 4.1.3
- Format: 4.1.1 (2022112604)

**Comment by gjb2048** [comment]
M4.1 and M4.0 versions patched.
