### ISSUE TITLE
Grid format - Is the ""Move section into grid" feature not available anymore in Moodle v4?

### ISSUE THREAD

**Issue by acquaalta** [gjbarnard/moodle-format_grid#185]
- Moodle: 4.1.3
 - Format: 401.1.1 (2022112604)
 - Chrome 114.0.5735.133 on MacOS

Hi,  
The Moodle 3 version of the Grid format included the "Move section into grid" feature, that converted the "General" section (also called "Section 0") into a photo in the grid. I don't see it anymore in the Moodle 4 version of the plugin. Wasn't the feature added in the Moodle v4 re-write of the plugin, or I am missing something?

Thanks

**Comment by gjb2048** [comment]
Dear @acquaalta 

In the re-write, for the most part, only features that are wanted and at the same time funded will be added.

Gareth

**Comment by gjb2048** [comment]
Implemented in M4.4 https://moodle.org/mod/forum/discuss.php?d=459308
