### ISSUE TITLE
Mouseover for shortened titles

### ISSUE THREAD

**Issue by thepurpleblob** [gjbarnard/moodle-format_grid#187]
When the tile title has been shortened, can we get a mouseover that shows the complete text?

This is to mitigate against course owners who haven't thought this through particularly well and the title that is displayed is insufficient to properly identify the content.

**Comment by thepurpleblob** [comment]
Much appreciated - enjoy the tennis :)

**Comment by gjb2048** [comment]
Needs backporting to M4.0.

**Comment by gjb2048** [comment]
M4.0 now on security updates, so won't backport that far.
