### ISSUE TITLE
Problems with creating multiple courses from template via CSV in Grid Format

### ISSUE THREAD

**Issue by wwobble** [gjbarnard/moodle-format_grid#189]
When we rename or create multiple courses via csv (upload courses) from a template which is in grid course mode we have two issues:
1. When creating: The new courses have no section images shown. The images are inside the section but not showing (when you change the section image and you choose "files from courses" you can see it's still there but not showing)
2. When renaming: The number of sections will be set to the Number you have in your default course settings e.g if you have there a default value of 4 and you rename a course (or multiple) via csv file the courses will have 4 sections and even if the course had more sections before they will be abandoned (hope that is the right english term) sections 

**To Reproduce**
Steps to reproduce the behaviour:
1. Website administration -> courses -> Upload courses
4. Rename a course in grid format with or less more sections than the default value and create a course via csv in grid format from a template course that have section images.
5. Open the renamed and the created course.
6. The renamed course will x sections where x is the default value for courses and the created course will have no section images showing.

**Expected behaviour**
The created course should look exactly like the template means the same images showing and the renamed course should have the same number of sections like before you start to rename it no matter what number of default sections you have set in website administration. 

**Screenshots**
Template course with pictures
![Template course with pictures](https://github.com/gjb2048/moodle-format_grid/assets/112091183/a3abb9c0-c548-4ea2-8231-3a9392ddabdb)
created course without pictures
![created course without pictures](https://github.com/gjb2048/moodle-format_grid/assets/112091183/43b3bcb7-fa68-48f9-8280-2f59525cac17)
Pictures in the section but not visible
![Pictures in the section but not visible](https://github.com/gjb2048/moodle-format_grid/assets/112091183/e4ca024d-ed5c-44fb-9ba7-f056345662ea)

**Versions (please complete the following information):**
 - Moodle: 4.1.5 Build: 20230814
 - Format: Release 401.1.1, Version 2022112604
 
**Additional context**
We use the csv to rename 200 courses in the beginning of a new year of school with different number of sections and we create a lot new courses via csv each year from different template courses.

**Comment by gjb2048** [comment]
Dear @wwobble,

Interesting.  To help me replicate, please supply sample CSV and MBZ files.

G

**Comment by gjb2048** [comment]
Also @wwobble,

Please first update to version 401.2.0, https://moodle.org/plugins/format_grid/401.2.0/29795, and test, as I think it will fix this issue, given:

1. Fix 'Previous/Next section arrows are incorrect for RTL languages' - #183.
2. Fix 'Last section not showing its image when editing'.
3. Convert 'numsections' to 'gnumsections' to facilitate both a course setting and flexible section management when editing.
4. Fix 'Undefined property' - #186.
5. Fix 'No sections showing when creating a course with the default number of sections'.
6. Fix 'Images are missing in the grid boxes when restoring a course' - #172.

And "Before reporting an issue, please ensure that you are running the current release for the major release of Moodle you are using." as stated in https://github.com/gjb2048/moodle-format_grid/blob/MOODLE_401/Support.md#reporting-issues.

G

**Comment by wwobble** [comment]
Ok thank you for the fast answer. Since I can not update myself because we have an external support company who runs the server and multiple moodle instances, I need to ask them first to update. I will take some time but I'll report back, when I checked if the issue still appears.

**Comment by gjb2048** [comment]
@wwobble Any news on this please?

**Comment by wwobble** [comment]
Sorry I'm still on trying to do all that what you ask me to do. Since I don't own all rights on our moodle (we are a school and some stuff is controlled by the admins of the whole region like updates) I need to ask others to help me. 
But I'm on it.

I have a .mbz and csv file for you if you still want them. 

Thanks for not forgetting that that issue exists. 

[CourseCreationViaCSV.zip](https://github.com/gjbarnard/moodle-format_grid/files/12739901/CourseCreationViaCSV.zip)

**Comment by gjb2048** [comment]
@wwobble Thanks, intriguing, I need to think about this.

**Comment by gjb2048** [comment]
@wwobble Ok, images fixed in V401.2.0 but not really the upload and number of sections, very, very complex!

**Comment by gjb2048** [comment]
Note to self 'process_gridsection'

**Comment by gjb2048** [comment]
Note, has taken around 5+ hours to solve!

**Comment by gjb2048** [comment]
@wwobble I think I have a fix with https://github.com/gjbarnard/moodle-format_grid/commit/9840a7bf828721d107f0784372102c9b7e38251e - if you have a test server, then either patch or install https://github.com/gjbarnard/moodle-format_grid/tree/MOODLE_401 and see if that fixes the problem for you.  Otherwise, wait for a release at some point in the future and update via testing before you update production.

**Comment by gjb2048** [comment]
Needs backporting to M4.0.

**Comment by gjb2048** [comment]
Now only backporting to M4.1, so closing.
