### ISSUE TITLE
Webp image causes an error and makes course inaccessible

### ISSUE THREAD

**Issue by Urpokarhu1** [gjbarnard/moodle-format_grid#190]
**Describe the bug**
When you upload a webp image to a grid it causes an error and makes course unaccessible

**To Reproduce**
Steps to reproduce the behaviour:
1. Edit Grid section
2. Add Webp image as section image
3. Save
4. Notice the error 
5. Try to access the course front page and notice that you can't

`Mime type is not supported as an image format in the Grid format - Mime type is not supported as an image format in the Grid format - document/unknown, itemid &gt; 270, filename &gt; uusikuva.webp and sectionid &gt; 270. Please report error details and the information contained in the php.log file to developer..`

**Expected behaviour**
Webp should be accepted without an error.

**Screenshots**
![image](https://github.com/gjb2048/moodle-format_grid/assets/53904029/f8f00836-580c-4160-81e6-fbdb260ead96)

**Versions (please complete the following information):**
 - Moodle: 4.1.5
 - Format: format_grid (401.1.1 2022112604)
 - Firefox 117

**Additional context**

**Comment by Urpokarhu1** [comment]
@gjb2048

**Comment by gjb2048** [comment]
Dear @Urpokarhu1,

Should be fixed in https://github.com/gjb2048/moodle-format_grid/commit/93719007b2b49018b3498b5c9da176e873f38f6c and will repair any damage.  Download a patched version from https://github.com/gjb2048/moodle-format_grid/archive/93719007b2b49018b3498b5c9da176e873f38f6c.zip.

G

**Comment by Urpokarhu1** [comment]
Thanks but I would like to see an official release.

**Comment by gjb2048** [comment]
@Urpokarhu1 Oh come on!  Please meet me half way and test, then I'll do an official release.

**Comment by gjb2048** [comment]
Dear @Urpokarhu1,

Any news on testing this please?

G

**Comment by Urpokarhu1** [comment]
Haven't had the chance yet.

**Comment by gjb2048** [comment]
@Urpokarhu1 Any news on testing this please?

**Comment by Urpokarhu1** [comment]
Hello,
I have now tested this and fix works, webp-image doesn't break course anymore

**Comment by gjb2048** [comment]
@Urpokarhu1 Thank you for testing and getting back to me.
