### ISSUE TITLE
 Flex containers' `justify-content` property options and keyboard shortcuts

### ISSUE THREAD

**Issue by SteffenLehmann** [gjbarnard/moodle-format_grid#191]
Hi Gareth J. Barnard,

Thank you for maintaining the grid format plugin; it is very useful. I’m working at Aalborg University in Denmark, and we are currently updating Moodle from 3.11 to 4.1.5. We have used the grid format in 3.11, but the flex containers' `justify-content` property has changed from center to between, which we would like to change.

However, changing the `justify-content` property does not seem to be the solution, as people have different preferences. Therefore, we would like to add a setting where you could select from the different `justify-content` property options, such as: start, center, space-between, space-around, and space-evenly.

Moreover, some keyboard shortcuts have also disappeared: arrow navigation between pop-up topics and the escape key (esc) does not open the highlighted topic when no topics are in the pop-up state.

How much would each improvement and all improvements cost?

For further correspondence, please contact me here: [stle@create.aau.dk](mailto:stle@create.aau.dk) 

Best,
Steffen L.

**Comment by gjb2048** [comment]
Dear @SteffenLehmann,

I've just sent you an eMail from my dot co dot uk eMail address, please let me know if you don't get it.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
@SteffenLehmann I've improved the keyboard control in https://github.com/gjb2048/moodle-format_grid/commit/ee34c8c032e022ca5f50daece05cf497d890dbef - as I feel that being an accessibility issue, then I should do this not as an enhancement but as a bug and that I'm morally responsible to do so.  The grid sections can now be tabbed to (when popup) forward (Tab) and backwards (Shift Tab).  The popup remains the same and can be closed, next / previous with the buttons - again tabbed to.  The original arrow key and Esc control was always a workaround as not standard accessible control.

**Comment by SteffenLehmann** [comment]
Hi @gjb2048,

Thank you for sending an offer, I will discuss the improvement cost with my project lead and get back to you.

I'm glad that you have added keyboard navigation back to the plugin.

You will hear from us through email, when we have made a decision.

Best,
SL

**Comment by gjb2048** [comment]
Related to: https://github.com/gjb2048/moodle-format_grid/issues/188

**Comment by gjb2048** [comment]
@SteffenLehmann Please note a change in the URL -> https://github.com/gjbarnard/moodle-format_grid/issues/191
