### ISSUE TITLE
Import a format_grid course into a format_topics course fails and produces "undefined method" error

### ISSUE THREAD

**Issue by Syxton** [gjbarnard/moodle-format_grid#193]
**Describe the bug**
Import a format_grid course into a format_topics course fails and produces "undefined method" error

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a course using the grid format and a course using the topics format.
2. Inside the topics format course, click the Reuse Course -> Import feature
3. Attempt to import everything from the grid course.

**Expected behaviour**
All imported items will be brought to the topics course.

**Screenshots**
![image](https://github.com/gjbarnard/moodle-format_grid/assets/989354/125ca849-fd4b-4c59-b3f9-5975d3e53acf)

**Versions (please complete the following information):**
 - Moodle: 4.2.2
 - Format: 402.2.1b
 - tested on Chrome latest version

**Comment by Syxton** [comment]
With full debugging on I see this:

`Did you remember to make the first column something unique in your call to get_records? Duplicate value '1' found in column 'typeid'.
line 1384 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
line 1679 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
line 1651 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
line 1630 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 97 of /mod/lti/service/gradebookservices/backup/moodle2/backup_ltiservice_gradebookservices_subplugin.class.php: call to moodle_database->get_record()
line 60 of /backup/moodle2/backup_subplugin.class.php: call to backup_ltiservice_gradebookservices_subplugin->define_lti_subplugin_structure()
line 247 of /backup/util/plan/backup_structure_step.class.php: call to backup_subplugin->define_subplugin_structure()
line 206 of /mod/lti/backup/moodle2/backup_lti_stepslib.php: call to backup_structure_step->add_subplugin_structure()
line 95 of /backup/util/plan/backup_structure_step.class.php: call to backup_lti_activity_structure_step->define_structure()
line 186 of /backup/util/plan/base_task.class.php: call to backup_structure_step->execute()
line 227 of /backup/moodle2/backup_activity_task.class.php: call to base_task->execute()
line 191 of /backup/util/plan/base_plan.class.php: call to backup_activity_task->execute()
line 145 of /backup/util/plan/backup_plan.class.php: call to base_plan->execute()
line 567 of /backup/controller/backup_controller.class.php: call to backup_plan->execute()
line 136 of /backup/util/ui/backup_ui.class.php: call to backup_controller->execute_plan()
line 136 of /backup/import.php: call to backup_ui->execute()
Exception - Call to undefined method format_topics::restore_gnumsections()

[More information about this error](https://docs.moodle.org/402/en/error/moodle/generalexceptionmessage)

Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 226 of /course/format/grid/backup/moodle2/restore_format_grid_plugin.class.php: Error thrown
line 137 of /backup/util/plan/restore_structure_step.class.php: call to restore_format_grid_plugin->process_gridsection()
line 123 of /backup/util/helper/restore_structure_parser_processor.class.php: call to restore_structure_step->process()
line 178 of /backup/util/xml/parser/processors/grouped_parser_processor.class.php: call to restore_structure_parser_processor->dispatch_chunk()
line 111 of /backup/util/helper/restore_structure_parser_processor.class.php: call to grouped_parser_processor->postprocess_chunk()
line 148 of /backup/util/xml/parser/processors/simplified_parser_processor.class.php: call to restore_structure_parser_processor->postprocess_chunk()
line 92 of /backup/util/xml/parser/processors/progressive_parser_processor.class.php: call to simplified_parser_processor->process_chunk()
line 189 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser_processor->receive_chunk()
line 277 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser->publish()
line ? of unknownfile: call to progressive_parser->end_tag()
line 178 of /backup/util/xml/parser/progressive_parser.class.php: call to xml_parse()
line 157 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser->parse()
line 110 of /backup/util/plan/restore_structure_step.class.php: call to progressive_parser->process()
line 186 of /backup/util/plan/base_task.class.php: call to restore_structure_step->execute()
line 98 of /backup/moodle2/restore_section_task.class.php: call to base_task->execute()
line 191 of /backup/util/plan/base_plan.class.php: call to restore_section_task->execute()
line 168 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
line 411 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
line 193 of /backup/import.php: call to restore_controller->execute_plan()`

**Comment by gjb2048** [comment]
@Syxton Thanks for the report and patch.  Would you like a credit in Changes.md?
