### ISSUE TITLE
Images and content are missing in the grid boxes when restoring a course

### ISSUE THREAD

**Issue by rschwarzinger** [gjbarnard/moodle-format_grid#197]
**Describe the bug**
similar to #172 (image of tile and its content are missing in duplicated course if picture of tile is not original)

**To Reproduce**
Steps to reproduce the behaviour:
1. new course with grid format
2. change image of tile with own picture
3. make some activities in this section
4. duplicate course
5. compare content in modified tiles
6. you will see no transfered content in the tile with own picture

**Expected behaviour**
duplicated course should be an exact copy

**Screenshots**
original course
![grafik](https://github.com/gjbarnard/moodle-format_grid/assets/76841651/5d8c14ad-ea68-4586-a00a-b3d2e34c44d2)

duplicated course
![grafik](https://github.com/gjbarnard/moodle-format_grid/assets/76841651/6101f542-0297-4f7d-8596-b4a30ec37227)

**Versions (please complete the following information):**
 - Moodle: 4.2.5 (Build: 20231222)]
 - Format: [Release 402.2.1b, Version 2023051005 für Moodle 4.2.5 (Build: 20231222)
 - different Browser and OS

**Comment by gjb2048** [comment]
Will be fixed in V402.2.2.
