### ISSUE TITLE
Grid Issue with Restoring Course When the Receiving Course Is Not Using the Grid Format

### ISSUE THREAD

**Issue by SteffenLehmann** [gjbarnard/moodle-format_grid#198]
Hi Gareth,

Thanks for maintaining a very useful plugin!

We at Aalborg University have found what might be a bug in the Grid format plugin.

When a teacher wants to use a course file that is backed up as an MBZ file, they can use the course reuse feature to restore it. The restore feature provides the teacher with two options for reuse: ‘Merge the backup course into this course’ and ‘Delete the contents of this course and then restore.’ However, if the course they are restoring into is not using the grid when using either of the two options, the restore fails. 

How to trigger it:
- Create a course (1) that is not using the grid format
- Create a second course (2) that is using grid.
   - Create a MBZ backup of the second course (2).
- Enter course (1) and find course reuse (more → reuse)
   - Select restore in the drop-down menu
   - Upload the MBZ file of course (2) and click on restore
   - Click continue
   - Select any option in the **Restore into this course** section and click continue
   - Complete the settings page without changing anything and perform the restore
   - ERROR
 
**Current behavior:**
The restore process fails and gives the following errors messages:
1. The first error message at 4.5
     - Exception: Call to undefined method format_topics::restore_gnumsections()
     - https://docs.moodle.org/401/en/error/moodle/generalexceptionmessage 
2. The second error message and the store process fails
    - A required parameter (contextid) was missing.
    - https://docs.moodle.org/401/en/error/moodle/missingparam 

**Expected behavior:**
A teacher should be able to restore a course with it being sensitive to course formats.

Grid version: 401.2.1b (2022112607)
Moodle version: Moodle 4.1.7 (Build: 20231211)

Best,
SL

**Comment by gjb2048** [comment]
Dear @SteffenLehmann,

Thanks for the report, this is a known issue and has been fixed by https://github.com/gjbarnard/moodle-format_grid/commit/b31c79ef45b4b5f60a37c284c445ea4518cccb4f.  I've just not gotten around to releasing on Moodle dot org yet, see: https://moodle.org/mod/forum/discuss.php?d=454379.

Kind regards,

Gareth

**Comment by SteffenLehmann** [comment]
Hi Gareth,

Thanks, we are looking forward to the update. 

Have a nice day. :)

Best,
SL.
