### ISSUE TITLE
Section summary does not display for the first section in the series of grids

### ISSUE THREAD

**Issue by zylene** [gjbarnard/moodle-format_grid#200]
Create a section after the default Moodle section (this will become the block in the grid) and add a summary to that section.
Create second section (or however many you want) and add summaries for those sections.
Save, turn off edit mode.

Click on the first grid block, the summary does not appear. Click on any of the following grid blocks (sections) and summaries do appear.

Turn editing on
Swap the first and section section placements (first is moved down, second is moved up).
Turn editing off

Click on the what now the first grid block (before it was the second), the summary does not appear. Click on any of the following grid blocks (sections) and summaries do appear.

Switch to another course format, like topics. All summaries appear.

For whatever reason the summary doesn't seem to appear for the section that is in position 1 of the grid. Work around is to create a dummy section and hide it from students. 

Expected behaviour:
When a summary is present for a section it should display when the section is selected.

Versions (please complete the following information):

    Moodle: 4.1.3+
    Format: Grid version of plugin: 401.2.2, 2022112608
    Browser and version: Firefox 122.00 and Chrome 120.0.6099.234 (Official Build) (arm64)

**Comment by gjb2048** [comment]
Dear @zylene,

Ok, thanks for the report.  Did you not see the contents of https://github.com/gjbarnard/moodle-format_grid/blob/main/.github/ISSUE_TEMPLATE/bug_report.md when creating the issue?  As again I have to ask:

Versions (please complete the following information):

Moodle: [e.g. 4.1]
Format: [e.g. 401.0.1]
Browser and version [e.g. Chrome Version 108.0.5359.125 (Official Build) (64-bit) on Windows 10]

This is SOOOO important!!!!!

**Comment by zylene** [comment]
apologies, the versions have been added to the original description

**Comment by gjb2048** [comment]
Cannot replicate on V401.2.2 of the Grid format on Moodle 4.1.8+ (Build: 20240125):

![Screenshot 2024-01-31 202659](https://github.com/gjbarnard/moodle-format_grid/assets/1058419/920986f0-a638-465a-b2c1-0bd6322a8b65)

![Screenshot 2024-01-31 202715](https://github.com/gjbarnard/moodle-format_grid/assets/1058419/1cb0ef7c-e9c1-4ea5-828b-ef50996f4182)


![Screenshot 2024-01-31 202743](https://github.com/gjbarnard/moodle-format_grid/assets/1058419/d59aecda-2ded-4bbf-a20c-f3b8eed6077f)


Do you have any Custom CSS that's causing this?  Does this happen in the Boost theme for you? (I'm using the Boost theme).

**Comment by zylene** [comment]
It does not happen in the Boost, it must be some custom css. Thanks for the quick attention to this.

**Comment by gjb2048** [comment]
No further action.
