### ISSUE TITLE
Glossary entry window opens several times in Grid

### ISSUE THREAD

**Issue by ralfhilg** [gjbarnard/moodle-format_grid#201]
Hi 
<img width="615" alt="26-02-2024_12-51-45" src="https://github.com/gjbarnard/moodle-format_grid/assets/41056305/07396727-5982-4c5d-a33a-51832e27764b">

we have an interesting scenario.

A glossary entry opens two to five times in a unilable simpletext in a course with Grid format

Moodle 4.1.8
Unilabel 4.3.1 (Build: 2023121300)
unilabeltype_simpletext | 2023111600
Grid 401.2.1b 2022112607

Any idea what can cause this problem?

I checked:
No problem with lable element.
No problem if the unilable is outside the grid tile in the 0-level.
I tried to reproduce it on an other platform with same versions but could not reproduce

I'm asking the unilable developer also

**Comment by ralfhilg** [comment]
It happens only in non ediiting mode

**Comment by gjb2048** [comment]
Dear @ralfhilg,

I've just done a quick test and cannot as so far replicate.  As actually my glossary entry is not linking for some reason.  However in the entry URL is there '/mod/' or '/course/'?  If the latter then the Grid format code comes into play, if the former then it does not.

G

**Comment by ralfhilg** [comment]
Thanks Gareth
The URL is https://....e/mod/glossary/showentry.php?eid=277&displayformat=dictionary
Swith your information we can exclude Grid as the problem.
