### ISSUE TITLE
Restrict access can cause no content in other sections to be shown.

### ISSUE THREAD

**Issue by Syxton** [gjbarnard/moodle-format_grid#202]
**Describe the bug**
If the General section of a course is restricted and not shown at all, it causes other available sections to not show their content.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make sure that Grid->Popup is set to NO.
2. Turn editing on.
3. Go to General section->Rectrict Access.  Add a Date restriction to a future date.  Click the eye icon to hide completely.
4. Save
5. Make sure there is a few sections in the course that are shown to students and contain content.
6. View the course as a student.
7. Click through the sections to see the content.

**Expected behaviour**
The student will not see the general section but they will see the available sections and the content in each section.

**Versions (please complete the following information):**
 - Moodle: 4.2+

**Additional context**
In my quick testing it seems to only cause issues if the General section is restricted and not shown.

**Comment by gjb2048** [comment]
Fixed.
