### ISSUE TITLE
Collapse all button non-responsive with course Edit Mode - WP 4.3.3

### ISSUE THREAD

**Issue by jprovasnik** [gjbarnard/moodle-format_grid#204]
I wanted to report a bug where the Collapse All button is not working  - the browser URL appends with a # sign, but the course sections do not collapse when this button is clicked, and the text does not change to "Expand all". This is for Moodle Workplace 4.3.3 with the Workplace theme -- I don't know if developers have access to even review issues if it's related Workplace, but figured I share this bug in case it's also happening on the non-workplace version of Moodle 4.3.3 as well. 

Steps to reproduce the behaviour:
1. Open a course that is in Grid format, with editing mode "off"
2. Click on any section tile to confirm it opens as expected -- close the pop up tile.
3. Click the "Edit Mode" tile at the top of the page to turn course editing mode "on"
4. Click the "collapse all" link in the General section
5. Confirm thee things: (1) the URL now has a "#" at the end, (2) the course sections did not toggle closed, and (3) the "collapse all" link did not change into an "Expand all" link.

**Expected behaviour**
Expected behavior is that upon clicking the "Collapse all" link while in Editing Mode: (1) all course sections wold toggle to a closed state and (2) the "Collapse all" link text would change to "Expand all"

**Screenshots**
This screenshot shows the expected outcome of clicking the "Collapse all" state (minus the fact that it would display "Expand all" if it was used to toggle all sections closed)
![Screenshot 2024-03-19 at 10 35 50 AM](https://github.com/gjbarnard/moodle-format_grid/assets/44345287/b4566489-3844-4943-a6ea-fb9a20c79228)

**Versions (please complete the following information):**
 - Moodle: WORKPLACE 4.3.3
 - Format: version 403.1.2 Build 2023101502
 - Browser and version: Chrome Version 122.0.6261.112 (Official Build) (x86_64) and Safari Version 17.2.1 (18617.1.17.11.12, 18617) on MacOS Ventura v 13.6.3

**Comment by gjb2048** [comment]
@jprovasnik Can't replicate in Moodle 4.3.3+ (Build: 20240315) - I don't have access to Moodle Workspace - it's a 'closed shop'.

**Comment by gjb2048** [comment]
@jprovasnik No reply, closing.
