### ISSUE TITLE
Block area and Link

### ISSUE THREAD

**Issue by wwobble** [gjbarnard/moodle-format_grid#207]
I would like to suggest two improvements that would I think would make a real difference:

1) Grid as linked image: We often use one course as an meta course to link to other courses where the real action happens. E.g. a course for a class from where all subjects (one per Grid) are reachable so students could always open the class course to get to the different subjects. It's more easy to navigate through moodle.  In the moment we put a link as activity (or in the description) inside a section of a grid. But that is One click to open the grid and an other to open the link. (the section is empty). So **I would love an checkbox or toggle in editing mode where I can make the grid itself a linked image so that when I click the grid the link opens directly instead of the section**. That would be awesome so some Grids would contain activities and others are only linked images that brings you to other courses or external websites.  

2) Block area inside a grid/section: Sometimes you have blocks that should be shown inside only one section so **it would be great if every section would have it's own area of blocks (maybe on the bottom/footer after all activities)** so I could put different blocks in different sections. I think about a Grid with individual progress bars or Calendar in one and glossar in a other and stuff. 

If it would be possible to add these features, that would be awesome. And thank you for the grid format in general.

**Comment by wwobble** [comment]
I added the labels by accident. I just wanted to add the label Enhancement.

**Comment by gjb2048** [comment]
Dear @wwobble,

1. This would be confusing - rejected.
2. Do you mean the Grid blocks or 'Block' regions that are defined by the theme?

G

**Comment by wwobble** [comment]
1. To bad. Thank you anyway.
2. I mean a Block region for Blocks like these https://moodle.org/plugins/?q=category:2 I guess thats the regions that are defined by the theme but you have in some activities such regions too e.g. in the book activity.

**Comment by gjb2048** [comment]
Dear @wwobble,

2. Block regions are defined by themes and are outside of the control of course formats.  Book uses a 'fake block' for its table of contents.

G
