### ISSUE TITLE
Titles in Navibar stil missing

### ISSUE THREAD

**Issue by mjencabh** [gjbarnard/moodle-format_grid#213]
**Describe the bug**
When using Grid as format, the title from "Text and Media" is still not showing in navibar.
It is only visible when in edit-mode.

**To Reproduce**
Steps to reproduce the behaviour:
Turn on edit mode - Add "Text and Media", put in a lable, and turn of edit mode -> Lable gone.

**Expected behaviour**
It should be showing like the other titles. (and did before)

**Screenshots**

**Versions (please complete the following information):**
 - Moodle: 4.4.1

**Comment by gjb2048** [comment]
Navbar?  The one at the top?  Screenshots please.  Both from what it was
before and what it is now.

**Comment by mjencabh** [comment]
Yes the course navigation bar.
Normally show all lables in course, it does this on the later 4.3 etc. just like in all other formats for Moodle.
Before your opdate the navigation bar was blank, so I guess this one slipped through.


Best regards
Michael

Fra: Gareth J Barnard ***@***.***>
Sendt: 1. august 2024 09:20
Til: gjbarnard/moodle-format_grid ***@***.***>
Cc: Michael Jensen (mjen.cb - Underviser - CB) ***@***.***>; Author ***@***.***>
Emne: Re: [gjbarnard/moodle-format_grid] Titles in Navibar stil missing (Issue #213)

Navbar? The one at the top? Screenshots please. Both from what it was
before and what it is now.

**Comment by gjb2048** [comment]
Course navigation bar?  There is the breadcrumb and the course index.
Screenshots please!

**Comment by mjencabh** [comment]
Sorry its the Course index, we just call it the other.
![When edit](https://github.com/user-attachments/assets/081275c3-9981-48c7-9d1c-5c7a5cbebe8b)
![After edit](https://github.com/user-attachments/assets/d4002953-75b3-4630-8d06-6c546cfe593e)

Test 2 and 3 is the Text and Media. Test 2 is with a placeholder lable (Text to Course index) and test 3 is without lable but with text inside, wich auto create Course index form first line. Non are showing whit Grid format.

Do you need more?

**Comment by gjb2048** [comment]
More please, so the actual labels when editing in the course, and
replication with the Custom (Topics) format.  Also why is 'test' showing,
what is that?

**Comment by gjb2048** [comment]
Also, what version of the Grid format?

**Comment by mjencabh** [comment]
Okay. 

Yes, there is no Course index showing from the activity "Text and Media", no matter if i use costum topic/lable or when it generates topic/lable from the first line in the text editor. 

its latest provided build : 404.1.0
"Test" is the URL activity, and has nothing to do with the problem. Teacher thought it would'nt show aswell, but its only Text and Media that are missing in the Course Index.

**Comment by gjb2048** [comment]
Cannot replicate:

![Screenshot 2024-08-01 134040](https://github.com/user-attachments/assets/7ce69792-e2f4-4b2e-8764-98c775743b04)

CI can be temperamental.  What happens if you log out, then clear the local browser cache for that site and log in again?

**Comment by mjencabh** [comment]
Hello again

ok its the same however we use Space as theme, and this is why we cant sew them.
Changing theme they did show as they should, sending this issue to the right place then.

Thx for your help.
