### ISSUE TITLE
Enhance teacher/admin view of the sections that have been hidden from students

### ISSUE THREAD

**Issue by golenkovm** [gjbarnard/moodle-format_grid#215]
**Is your feature request related to a problem? Please describe.**
When course setting `Hidden sections` is set to `Hidden sections are shown as not available` students can easily identify the sections that are hidden. However, when teachers or admins view the list of sections they see no badge/marks which makes their navigation a bit more difficult. To see if a section is hidden for students they need to click on the section icon and check if the `Hidden from students` badge is there.

Student's view:
![image](https://github.com/user-attachments/assets/38b7404e-09ca-45cf-9d78-665fe0cc4106)

Teacher's view:
![image](https://github.com/user-attachments/assets/16ab8eaf-ec94-49a9-a863-ce13d7a016fc)

**Describe the solution you'd like**
It would be great to enhance UX for teachers and admins and mark hidden sections on the course page. As a potential solution the hidden sections could be greyed out, eg:
![image](https://github.com/user-attachments/assets/168fb38c-5757-4d65-a209-e74173ccc02c)

Ideally this should be extendable. For instance, the tile attribute `class` would have a specific class passed so it would be possible to override the css for the hidden section tile in theme.

**Describe alternatives you've considered**
The sections could be also marked with the same `Hidden from students` badge to make the views consistent.

**Versions you are currently using (please complete the following information):**
 - Moodle: 4.1.11+ (Build: 20240719)
 - Format: 401.2.4 2022112610

**Funding**
Catalyst IT is happy to assist with the implementation and work on the pull request for this enhancement.

**Comment by gjb2048** [comment]
@golenkovm Interesting, how does the Topics / Custom format solve this when editing mode is off?

**Comment by golenkovm** [comment]
@gjb2048 thank you for your prompt reply.

As a student you can see the badge `Not available` and the section content is not displayed:
![image](https://github.com/user-attachments/assets/e658a972-d493-46e3-b121-88b5c27bead3)

As a teacher or as an admin you can see the badge `Hidden from students` and if you expand the section the activities are marked as well:
![image](https://github.com/user-attachments/assets/09044c97-036e-4ac3-bedb-fd1ea3eb167b)

Also, there is a `hidden` attribute in `class` for that section so it's possible to apply some custom CSS via a theme:
![image](https://github.com/user-attachments/assets/1299d42d-02c9-4161-aa6b-12cb11540f20)

**Comment by golenkovm** [comment]
Thanks heaps @gjb2048 
Would it be possible to backport it to MOODLE_401 branch?

Kind regards,
Misha

**Comment by gjb2048** [comment]
@golenkovm Will do when I do a backporting process in the future for a release.  Takes time to setup and do, so I only do when I need to.
