### ISSUE TITLE
Restore skips sections if hidden sections are present

### ISSUE THREAD

**Issue by Syxton** [gjbarnard/moodle-format_grid#216]
**Describe the bug**
If a course contains hidden sections between visible sections, the visible sections that are after the hidden sections will not be restored.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a course with 7 sections.
2. Place content in all 7 sections.
3. Hide sections 3 and 4
4. Backup and Restore as a new course.
5. I am seeing section 1-4 correctly, but section 5 is empty and the course format is counting only visible sections and is set to 5 so Section 6-7 (also empty) are not shown at all.

**Expected behaviour**
The restored course should look exactly like the original course.

**Screenshots**

**Versions (please complete the following information):**
 - Moodle: 4.2
 - Format: Grid
 
**Workaround:**
 - Before backing up original course, either unhide all hidden sections OR move hidden sections to the bottom of the course.

**Comment by gjb2048** [comment]
@Syxton What version of Grid please?

**Comment by Syxton** [comment]
@gjb2048 Sorry.  we are running 402.2.2

We are updated to Moodle 4.4.2+ tomorrow and will be on grid 404.1.0 then.  Doesn't seem to be an issue in my testing in that version.

**Comment by gjb2048** [comment]
Odd then as the restore code is identical:

![Screenshot 2024-08-21 192932](https://github.com/user-attachments/assets/e00fb97a-5a3a-4b45-98cd-f074d09cd87d)

**Comment by gjb2048** [comment]
Even https://github.com/gjbarnard/moodle-format_grid/issues/189... thus my earlier compare was with the current development versions.  Thus upgrade to 402.2.3 as published on Moodle dot org and see if you can replicate.

**Comment by Syxton** [comment]
@gjb2048 This is going to take some further testing.  I was able to recreate it over and over this morning in a single course, but I haven't been able to recreate it in my test courses or test environment.  Please disregard for now.

**Comment by gjb2048** [comment]
@Syxton Not even using the same MBZ from that single course?

**Comment by Syxton** [comment]
@gjb2048 All the backups of that single course still fail, only the backup once I moved the two hidden sections to the bottom of the course worked.  But following the Recreation steps in a new course didn't cause the error...so I'm still digging to find what is happening in this one course.

**Comment by gjb2048** [comment]
@Syxton Any progress in replicating?

**Comment by Syxton** [comment]
@gjb2048 I haven't had a chance to get back to look at this.  It is on my list though

**Comment by Syxton** [comment]
@gjb2048 I would say that you can close this.  I've not had it happen on any other course.

**Comment by gjb2048** [comment]
@Syxton Thanks.
