### ISSUE TITLE
Grid format images displayed below and behind grid boxes

### ISSUE THREAD

**Issue by dragos5436** [gjbarnard/moodle-format_grid#217]
**Describe the bug**
After our last Moodle upgrade we noticed that in courses where the grid format is in use, the images supposed to be inside the boxes are now displayed below the boxes and/or behind the boxes just below.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any course using the grid format or set the format to grid;
2. Scroll down to see the grid boxes;
3. Notice the misplaced images.

**Expected behaviour**
Images should be displayed within the borders of the grid boxes.

**Screenshots**
Here is an example of a course before and after the bug:

Before (expected behaviour):
![image](https://github.com/user-attachments/assets/1c9b35c7-fb7d-4dd0-b5f4-7f5f3bc8cc87)

After (current behaviour):
![image](https://github.com/user-attachments/assets/af5db6d2-8f92-4a14-b322-af5f031c6b9a)

**Versions (please complete the following information):**
 - Moodle: 4.4.2+ (Build: 20240823)
 - Format: 2024032902
 - Browser: Tested in the latest version of Chrome, Edge and Firefox, was able to replicate the issue in each one.

**Additional context**
Some further digging revealed that the bug has been present since commit https://github.com/gjbarnard/moodle-format_grid/commit/bc5cb698c5da4945aef280f79ba12d2b2957e15b . Using any version before this resolves the issue and the images are in the right place.

1) Could you please investigate whether you are able to reproduce?

2) We have over 800 courses in our Moodle using this format and we are looking to get this sorted asap. Is there any quick fix we can apply (such as custom CSS for instance) before a proper solution is released?

Thank you.

Kind regards,
Dragos

**Comment by dragos5436** [comment]
Hi @gjb2048 , we are currently using the main branch of the grid format plugin in our production build. It currently has the same version as the one I mentioned above. The commit I was talking about was released on this branch on Aug 14th:
![image](https://github.com/user-attachments/assets/99ffa8a8-62be-44c5-a20e-d8e7c201f6cf)

Are you saying this is a development branch and we should not be using it?

**Comment by gjb2048** [comment]
Also what theme are you using?

**Comment by gjb2048** [comment]
And looking at / interpreting your screen shots then I think it is a theme issue / conflict.

**Comment by gjb2048** [comment]
And.... do you always update your production server without first updating your test server and checking there?

**Comment by dragos5436** [comment]
Thank you for the information above. I think after the upgrade to Moodle 4.4 we switched the grid format branch from MOODLE_403 to main. Are you recommending we use, for instance, a tag such as 'V404.1.0' for Moodle 4.4?

We are currently using our own custom theme for UCL. You believe there is a conflict between that and the grid format that is causing this issue?

And yes, we do have test environments where we test updates before releasing to production, but we don't test every new update released by plugin developers. I assume the problem was we were not aware this was a development branch and did not worry testing the work on it.

**Comment by gjb2048** [comment]
1. Always use tagged versions unless wanting to support me by occasionally testing what is being developed.
2. Yes.
3. You should test every update by a plugin developers as they / we are only human.

**Comment by gjb2048** [comment]
My mistake, couldn't see the possibility of https://github.com/gjbarnard/moodle-format_grid/commit/9b12eaf1e0435156551e102b49b138a9060ea0ac being the cause.

**Comment by dragos5436** [comment]
Closing as fixed by subsequent commits
