### ISSUE TITLE
Version 404.1.2 adhoc task fails

### ISSUE THREAD

**Issue by Syxton** [gjbarnard/moodle-format_grid#222]
**Describe the bug**
Adhoc task failed: format_grid\task\update_displayed_images_adhoc,Call to undefined function format_grid\course_get_format()
Backtrace:
* line 670 of /course/format/grid/classes/toolbox.php: call to format_grid\toolbox::update_the_displayed_images()
* line 58 of /course/format/grid/classes/task/update_displayed_images_adhoc.php: call to format_grid\toolbox::update_displayed_images()
* line 47 of /course/format/grid/classes/task/update_displayed_images_adhoc.php: call to format_grid\task\update_displayed_images_adhoc::do_update_displayed_images_task()
* line 519 of /lib/classes/cron.php: call to format_grid\task\update_displayed_images_adhoc->execute()
* line 348 of /lib/classes/cron.php: call to core\cron::run_inner_adhoc_task()
* line 371 of /lib/classes/cron.php: call to core\cron::run_adhoc_task()
* line 154 of /admin/cli/adhoc_task.php: call to core\cron::run_failed_adhoc_tasks()

**To Reproduce**
Steps to reproduce the behaviour:
1. after install, ad hoc tasks start failing.

**Versions (please complete the following information):**
 - Moodle: 4.4

**Comment by gjb2048** [comment]
Strange given https://github.com/gjbarnard/moodle-format_grid/blob/main/classes/task/update_displayed_images_task.php#L47 - is your Moodle in maintenance mode to prevent changes to the course course format setting?

**Comment by gjb2048** [comment]
@Syxton And.... what version of the format!

**Comment by gjb2048** [comment]
Oh grrr, I forgot a backslash here... https://github.com/gjbarnard/moodle-format_grid/blob/main/classes/task/update_displayed_images_task.php#L50

**Comment by gjb2048** [comment]
@Syxton And there is never such a thing as 'latest release' as your version could be different to mine as you're not aware of a 'latest' that I may have just published whilst what you think is 'latest' but actually no longer actually is.

**Comment by gjb2048** [comment]
@Syxton Then in the future when people search for problems, they can't then be sure that the issue has been addressed as all they know its that its in the 'latest' version which they think they may have but actually don't and therefore spend ages being confused without having the facts.  Therefore 'always' state the actual version please!!!!

**Comment by gjb2048** [comment]
Humm... strange that it worked in testing though... odd.

**Comment by gjb2048** [comment]
@Syxton Having said about the backslash though, it's odd given the stack trace as https://github.com/gjbarnard/moodle-format_grid/blob/main/classes/task/update_displayed_images_adhoc.php#L58 should never happen in a non-grid format course because the adhoc task would not be scheduled for a course that isn't a grid one by https://github.com/gjbarnard/moodle-format_grid/blob/main/classes/task/update_displayed_images_task.php#L47.

**Comment by gjb2048** [comment]
Or perhaps I've not missed a backslash as everywhere else doesn't use one, even with a name space.

**Comment by gjb2048** [comment]
@Syxton How are you running cron exactly please?

**Comment by gjb2048** [comment]
@Syxton Okay, I've tried to replicate and cannot:

```
Execute adhoc task: format_grid\task\update_displayed_images_adhoc
Adhoc task id: 14
Adhoc task custom data: "2"
... started 17:32:40. Current memory use 58.1 MB.
Executing Grid update displayed images adhoc task on course id 2.
... used 84 dbqueries
... used 1.2127048969269 seconds
Adhoc task complete: format_grid\task\update_displayed_images_adhoc
Ran 1 adhoc tasks found at Sat, 28 Sep 2024 17:32:40 +0100
Cron run completed correctly
```

Running via UI cron.

**Comment by gjb2048** [comment]
Ah, okay, with cli cron:

```
Adhoc task failed: format_grid\task\update_displayed_images_adhoc,Call to undefined function format_grid\course_get_format()
Backtrace:
* line 670 of \course\format\grid\classes\toolbox.php: call to format_grid\toolbox::update_the_displayed_images()
* line 58 of \course\format\grid\classes\task\update_displayed_images_adhoc.php: call to format_grid\toolbox::update_displayed_images()
* line 47 of \course\format\grid\classes\task\update_displayed_images_adhoc.php: call to format_grid\task\update_displayed_images_adhoc::do_update_displayed_images_task
()
* line 519 of \lib\classes\cron.php: call to format_grid\task\update_displayed_images_adhoc->execute()
* line 302 of \lib\classes\cron.php: call to core\cron::run_inner_adhoc_task()
* line 128 of \lib\classes\cron.php: call to core\cron::run_adhoc_tasks()
* line 186 of \admin\cli\cron.php: call to core\cron::run_main_process()

Ran 1 adhoc tasks found at Sat, 28 Sep 2024 17:41:06 +0100
```

Therefore the UI cron loads with /course/format/lib.php that has 'course_get_format()' and the CLI version doesn't!

**Comment by gjb2048** [comment]
Okay, have a fix:

```
Execute adhoc task: format_grid\task\update_displayed_images_adhoc
Adhoc task id: 16
Adhoc task custom data: "2"
... started 17:53:36. Current memory use 52.4 MB.
Executing Grid update displayed images adhoc task on course id 2.
... used 86 dbqueries
... used 0.76198315620422 seconds
Adhoc task complete: format_grid\task\update_displayed_images_adhoc
Ran 1 adhoc tasks found at Sat, 28 Sep 2024 17:53:36 +0100
```
