### ISSUE TITLE
Orphaned sections problem when adding sections

### ISSUE THREAD

**Issue by ska13000** [gjbarnard/moodle-format_grid#223]
**Describe the bug**
When you are in course edit mode and add a section, the number of sections in the course parameters changes to 1. When you return to the course, you get the following error message on a red background displayed at the top of the course -> “Warning: Course has 2 orphaned section(s) with content. Resolve as soon as possible. Note: Importing into this course from another will turn orphaned sections into real ones - there is no current solution to this!”. To solve this problem, you need to manually go back to the course settings and update the number of sections.

**To Reproduce**
1- go to editing mode
2- add a section
3- return to course view mode
4- the above error message appears at the top of the course page

**Expected behavior**
after adding a section, the error message should not appear and the course sections should not be orphaned.

**Versions :**
moodle 4.4.3+
plugin 404.1.2.5 or 404.1.2
browser Firefox Mac 130.0.1 (64 bits) or Safari Version 18.0 (18619.1.26.111.10, 18619)

_Translated with DeepL.com (free version)_

**Comment by gjb2048** [comment]
@ska13000 Thanks for the report.  Fix for M4.4 implemented.

**Comment by ska13000** [comment]
Thanks a lot
