### ISSUE TITLE
Getting error with default image settings

### ISSUE THREAD

**Issue by JJ-95** [gjbarnard/moodle-format_grid#225]
**Describe the bug**
Grid format default image settings changes gives error and breaks the img link.

Steps to reproduce the behaviour:
1. Create course with grid format and add image to grid card
2. Change the course fromat to something else like collopsed topics
3. Go to site administration and grid format default settings
4. Change one of the image default settings (Default width of the image container, Default ratio of the image container relative to the width, Displayed image type) and press save changes then the error will show up
5. Then go to the course and change grid format back
6. Now the grid image is broken

**Expected behaviour**
No error should be given.

**Screenshots**
![image](https://github.com/user-attachments/assets/5ee037ce-4f8c-4bb3-aa33-775fef336f9e)
![image](https://github.com/user-attachments/assets/3097547a-9509-46b4-aec8-30ef97f5f9b2)

**Versions (please complete the following information):**
 - Moodle: 4.1
 - Format: 401.2.3
 - Browser and version: Chrome Version 129.0.6668.90 (Official Build) (64-bit) on Windows 10

**Comment by gjb2048** [comment]
In theory fixed by #211 in V401.2.4 - also "Before reporting an issue, please ensure that you are running the current release for the major release of Moodle you are using." - ref: https://github.com/gjbarnard/moodle-format_grid/blob/MOODLE_401/Support.md#reporting-issues.
