### ISSUE TITLE
Error Class "format_base" not found

### ISSUE THREAD

**Issue by cedrinetille** [gjbarnard/moodle-format_grid#229]
**Describe the bug**
Hi !
We upgraded one of our customers' Moodle instances from version 4.2 to 4.5. However, as we deploy, we get the following error with the format_grid plugin: `Class “format_base” not found`

**Versions (please complete the following information):**
 - Moodle: 4.5 (2024100700.00; )
 - Format: 405.0.1 (2024101500;(

**Additional context**
Thanks to fix it !

**Comment by gjb2048** [comment]
@cedrinetille I suspect the upgrade process done correctly.  Try again.

**Comment by gjb2048** [comment]
@cedrinetille If no reply, then I'll close this issue.

**Comment by cedrinetille** [comment]
@gjb2048 Thanks for your answer, I'll check and come back to you as soon as possible.

**Comment by cedrinetille** [comment]
Hi ! 
I'm closing this issue as the customer decided to drop the plugin
