### ISSUE TITLE
Embedded videos continue playing

### ISSUE THREAD

**Issue by FuzzyHero** [gjbarnard/moodle-format_grid#25]
When playing embedded youtube videos with the 'Fit the section popup to the window' set to yes the video continues to play if you click the next or previous arrow or close the section.

**Comment by gjb2048** [comment]
There is nothing I can do about this.

**Comment by gjb2048** [comment]
Ref: CONTRIB-3471 -> https://tracker.moodle.org/browse/CONTRIB-3471.

Unless you know of a way client side JavaScript can send a message to the YouTube API to stop playing a video and for the format to know that there is an embedded YouTube module.

In any event the words 'Fit the section popup to the window' indicate that this is a module setting and therefore an issue with the module and not the course format.

**Comment by gjb2048** [comment]
Decided to have this open and CONTRIB-3471 closed.

**Comment by nmoller** [comment]
Using the link to the youtube API from
[stackoverflow](http://stackoverflow.com/questions/13682049/cant-stop-youtube-video-in-hidden-div-playing-in-the-background)
that means [youtubeAPI](https://developers.google.com/youtube/iframe_api_reference#Getting_Started)
passing it in a the html content of a label. From there you are able to control it from the events of the page. 
It is far away from being a solution but I think that points that something could be done to get a finer control over the video player.

**Comment by gjb2048** [comment]
@FuzzyHero Can't really fix this.
