### ISSUE TITLE
Not being able to move from one section to another using HTML links

### ISSUE THREAD

**Issue by zahrah-** [gjbarnard/moodle-format_grid#38]
Hello Gareth,

Moodle 3.1.2 (Build: 20160912),  GRID format: 3.1.1.0 2016060701

I'm trying out the Grid plugin for a new course. It's quite nice and suits the course best. Thank you. I just have one problem I'm trying to sort out:
I have set up the first section to serve as an index to topics covered in other sections and I would like to use HTML links to transit to the relevant section, but I can't seem to get it to work as desired. 

I'm using these settings:
Course Layout: Show all sections on one page
Fit section popup to window: Yes

I've noticed that as mentioned on the plugin page by another user that if the Course Layout is set to: Show one section per page then it works fine. But with the way I have it set the link does not work if opening in the same window. However, if I set the link to open in a new window it works, but I prefer the student to remain on one screen. 
The format of the link I'm using is: course id#section-number as seen in the screenshots below. (These are from my test system not the one with the index of topics...)
![grid_link1](https://cloud.githubusercontent.com/assets/8460383/20539119/55cc93a0-b0ca-11e6-9c2e-1211c0e948a4.png)

When it opens in a new window:
![grid_link2](https://cloud.githubusercontent.com/assets/8460383/20539127/5b05a762-b0ca-11e6-8afa-ce836250caf8.png)

Is it possible to do what I'm trying to do?

Thanks in advance.

Regards.
sali

**Comment by gjb2048** [comment]
So in effect you want a link that opens up a specific section and shows its content in the grid box?

**Comment by zahrah-** [comment]
Thanks for the quick response.
Yes, I think that's it.
If the topic in the Index section (section 1) is covered in section 5, then when I click the link for the topic, if it brings up section 5 that would be great - ideally on the same screen (and perhaps the same grid box pop up area). 
Hope I've explained it clearly.

**Comment by gjb2048** [comment]
Fair enough, I'll look for a solution when I get time.

**Comment by zahrah-** [comment]
Thanks!

**Comment by gjb2048** [comment]
Currently can't be done as grid click functionality is established in module.js in JavaScript.  There is no code to detect and act upon links with some sort of attribute to identify it as a Grid show shadebox link.

**Comment by zahrah-** [comment]
Gareth, thanks for looking into it.
I'll use one of the workarounds for now - open in a new window or use the "Show one section per page" option.
Unfortunately I won't be able to consider the funded enhancement at this time as my work is generally on a voluntary basis for non-profit organizations.
Keep up the great work.
Best regards.
sali
