### ISSUE TITLE
Screenreader Not Reading Lightbox Content

### ISSUE THREAD

**Issue by mdelonge** [gjbarnard/moodle-format_grid#68]
Here is the link to a screen recording of NVDA going through grid format: [https://ensemble.nmc.edu/Watch/Dn86BqNt](https://ensemble.nmc.edu/Watch/Dn86BqNt)

To start I used the tab key to navigate down to the first topic "Syllabus, Schedule & Announcements" and used the Enter key to open it. (10 second mark of video)

You can hear that once the topic is opened and the popup of information is there the screenreader doesn't see it or read it.

I use my arrow keys to try and navigate, but you can hear that I am continuing to navigate through the other topics on the home page. You can see this when I get to Ch. 2 Module, then it goes to Ch. 3, and then Ch. 4. (28 second mark of video)

Then I tried navigating with the tab key, you can see now that when I tab between the grid choices the popup window reflects which topic I am on, but I still can't get into the popup to read the content. (56 second mark of the video)

Finally, I try the esc key. Which just closes the popup, and was never able to read any content in the popup.

We have also had a high-level, expert user of JAWS and NVDA try to read the Grid Format and he has the same issues that we have demonstrated in this video.   Please let us know if there are is more information we can provide.  Thanks for your time.

**Comment by gjb2048** [comment]
Thanks, do you have a download link for the video so I can store locally and not burn up my limited broadband allowance.

**Comment by mdelonge** [comment]
[GridNVDATest.zip](https://github.com/gjb2048/moodle-format_grid/files/1690850/GridNVDATest.zip)
 Attached.

**Comment by gjb2048** [comment]
Ok, not viewed yet, but when looking at a different issue for a client I found:

````
        if (!empty($USER->profile['accessible'])) {
            return parent::print_multiple_section_page($course, $sections, $mods, $modnames, $modnamesused);
        }
`````

therefore indicating that perhaps in this instance the format is not suitable in all cases.  Therefore if the user profile has 'accessible' set then it will display as per the standard topics format instead, which may help in this case.

**Comment by mdelonge** [comment]
We looked over our user profiles and did not see a field or spot to indicate "accessible" in our Moodle set up.  After reviewing some of the Accessibility Guidelines, the grid format will need to work "out of the box" to meet ADA compliance without flagging students.  So, I don't believe the solution above will work for us.  Do you have any other thoughts on how to make a screenreader read the lightbox content?

**Comment by gjb2048** [comment]
You have to add it as a custom user profile field: https://docs.moodle.org/34/en/User_profile_fields.

I know this is not a long term solution, but its the best I can do at the moment.

**Comment by gjb2048** [comment]
Regarding your 'out of the box' comment, you could employ a developer well versed in accessibility to make the changes and then send them back to me to contribute back to the community - as long as they were accessibility changes only and not pertaining to changing the functionality.

**Comment by sharpchi** [comment]
Just wanted to confirm a couple of things .... if you try to tab through a page, the browser should jump from heading/link to heading/link as a very basic way of imaging how the screen reader will progress through a page. Using the keyboard only method it's not possible to access the content in the pop-up.

Your suggestion about using the $USER->profile['accessible'] does work. Like you say, the system admin needs to create the profile field manually, but that's not difficult.

For our own solution, I extend the grid format renderer and to use user preferences which we use for various accessibility theme related things - follow the link to see how we did that https://github.com/sharpchi/moodle-local_accessibilitytool

**Comment by gjb2048** [comment]
@sharpchi The M4.0 version no longer uses the lightbox code and if it does in the future, will then be a re-write.
