### ISSUE TITLE
"found more than one record" for format_grid_summary table

### ISSUE THREAD

**Issue by thepurpleblob** [gjbarnard/moodle-format_grid#97]
plugin version 2018121902

We're seeing a lot of notices logged for duplicate records in the above table. We see many cases of three entries for the same course with a strangely similar pattern. 

```
mysql> select * from mdl_format_grid_summary where courseid=17269;
+------+-------------+----------+
| id   | showsummary | courseid |
+------+-------------+----------+
| 2813 |           0 |    17269 |
| 2853 |           1 |    17269 |
| 2854 |           1 |    17269 |
+------+-------------+----------+
3 rows in set (0.00 sec)

mysql> select * from mdl_format_grid_summary where courseid=17318;
+------+-------------+----------+
| id   | showsummary | courseid |
+------+-------------+----------+
| 2845 |           0 |    17318 |
| 2849 |           1 |    17318 |
| 2850 |           1 |    17318 |
+------+-------------+----------+
3 rows in set (0.00 sec)

mysql> select * from mdl_format_grid_summary where courseid=17270;
+------+-------------+----------+
| id   | showsummary | courseid |
+------+-------------+----------+
| 2855 |           0 |    17270 |
| 2856 |           1 |    17270 |
| 2857 |           1 |    17270 |
+------+-------------+----------+
3 rows in set (0.00 sec)
```

The line where it fails is https://github.com/gjb2048/moodle-format_grid/blob/master/lib.php#L2020

I haven't spend a huge amount of time on it but the code looks perfectly sensible... any thoughts?

**Comment by gjb2048** [comment]
Hi Howard,

I think, just think this could be a multithread concurrent process issue where two people do the same thing at the same time and the code is executed twice.  Or some quick refresh etc. with an overloaded DB.  I've noticed that the theme renderers are always instantiated more than once on a page load, so same thing.

Solution will be some sort of thread safe block whereby only one thread can execute at any one time.  Humm!  Need to look at ob_start etc.

G

**Comment by universityofglasgow** [comment]
Yeh - this sort of thing is why transactions where invented I suppose :-D

**Comment by gjb2048** [comment]
@universityofglasgow How would transactions help here when the code is reading existing data and then making a decision (transactions in Moodle -> https://moodle.org/mod/forum/discuss.php?d=135847) - this is a concurrent programming in PHP issue.

**Comment by gjb2048** [comment]
Note to self: https://docs.moodle.org/dev/Lock_API

**Comment by gjb2048** [comment]
@thepurpleblob Please could you patch your version of the Grid format with https://github.com/gjb2048/moodle-format_grid/commit/cd6ca689e1c58026e8320d605930981695f79b82 after removing any duplicates and see if that happens.  Test server test first please.

**Comment by thepurpleblob** [comment]
We've not seen this anywhere except on our live site but I'm happy to give it a go. We're battling some intermittent performance issues right now, so it might take a while. I'm getting nasty looks when I say I'm changing something!

**Comment by gjb2048** [comment]
@thepurpleblob Still an issue?

**Comment by gjb2048** [comment]
@thepurpleblob Still an issue???

**Comment by gjb2048** [comment]
No response, closing.
